#!/usr/bin/env ruby

$: << File.join(File.dirname(__FILE__), "..", "lib")

require 'henchman'

EM.synchrony do
  10.times do
    Henchman.publish("test", {:time => Time.now.to_s})
    EM::Synchrony.sleep 0.5
  end
  EM.stop
end
