#!/usr/bin/env ruby

$: << File.join(File.dirname(__FILE__), "..", "lib")

require 'henchman'

EM.synchrony do
  Henchman::Worker.new("testpub") do
    puts message.inspect
    puts headers
  end.subscribe!
end
